### PR TITLE
Filter feature

### PR DESCRIPTION
**Pull request by bbollen23**
Here is the old pull request that was closed since dev was deleted: https://github.com/visdesignlab/loonar/pull/46

Does this PR close any open issues?
Closes #

The bugs associated with the current state of filtering:
Certain plots have issues loading due to NaN values.

Give a longer description of what this PR addresses and why it's needed
Filtering by certain attributes is a key component for our collaborators to make inferences,
comparisons, and help clarify existing data. The filter sidebar selector is a view which helps
accomplish this.

Provide pictures/videos of the behavior before and after these changes (optional)
If you have questions reach out.

Have you added or updated relevant tests?
 Yes
[X ] No changes are needed
Have you added or updated relevant documentation?
 Yes
[X ] No changes are needed
Are there any additional TODOs before this PR is ready to go?
TODOs:

 Update other other components / backend data via filters
 Add SPLOM selector
 Fix bugs mentioned above in open issues

### CODE REVIEW

**Comment by Luke-Schreiber** [comment]
I've created renewed the pull request for this code. I've resolved most of the original issues mentioned in the first review. Let me know if you have any questions, reviews, edits, etc. Thanks.

**Review by Dev-Lan — CHANGES_REQUESTED** [review]
So the things we discussed to fix on this PR:

- [ ] refactor range dialog into a new component instead of duplicating code
- [x] Add dark mode support (for modal and plot selection menu)
- [x] fix error handling code (that I broke), or just delete it
- [x] fix the experiment switching error - the plot's to display and current filters should be reset.

Then we can merge this into dev :), nice work!

**Comment by Luke-Schreiber** [comment]
Fixed all PR fixes plus additional little bugs. As we discussed, we still need to write issues for things like: 
- selecting within the vgplot
- convert to filter functionality
- track-level attributes and lineage-level attributes

Let me know if these changes look good to you and we can merge.

**Comment by Luke-Schreiber** [comment]
Merged!

**Pull request merged**
